package com.jojowonet.modules.order.adapters;

import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public class HistoryBkOrderSettlementDetail extends JBean {

	public HistoryBkOrderSettlementDetail(Record record) {
		super(record);
	}

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setSettlementId(String settlementId) {
		set("settlement_id", settlementId);
	}

	public String getSettlementId() {
		return get("settlement_id");
	}

	public void setOrderId(String orderId) {
		set("order_id", orderId);
	}

	public String getOrderId() {
		return get("order_id");
	}

	public void setType(String type) {
		set("type", type);
	}

	public String getType() {
		return get("type");
	}

	public void setSettlementTime(java.util.Date settlementTime) {
		set("settlement_time", settlementTime);
	}

	public java.util.Date getSettlementTime() {
		return get("settlement_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateName(String createName) {
		set("create_name", createName);
	}

	public String getCreateName() {
		return get("create_name");
	}

	public void setEmployeId(String employeId) {
		set("employe_id", employeId);
	}

	public String getEmployeId() {
		return get("employe_id");
	}

	public void setEmployeName(String employeName) {
		set("employe_name", employeName);
	}

	public String getEmployeName() {
		return get("employe_name");
	}

	public void setSumMoney(java.math.BigDecimal sumMoney) {
		set("sum_money", sumMoney);
	}

	public java.math.BigDecimal getSumMoney() {
		return get("sum_money");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}

	public String getRemarks() {
		return get("remarks");
	}

	public void setServiceMeasures(String serviceMeasures) {
		set("service_measures", serviceMeasures);
	}

	public String getServiceMeasures() {
		return get("service_measures");
	}

	public void setCostDetail(String costDetail) {
		set("cost_detail", costDetail);
	}

	public String getCostDetail() {
		return get("cost_detail");
	}

	public void setSiteId(String siteId) {
		set("site_id", siteId);
	}

	public String getSiteId() {
		return get("site_id");
	}

	public void setRatio(java.math.BigDecimal ratio) {
		set("ratio", ratio);
	}

	public java.math.BigDecimal getRatio() {
		return get("ratio");
	}

}
