package com.jojowonet.modules.order.adapters;

import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public class HistoryBkOrderFeedback extends JBean {

	public HistoryBkOrderFeedback(Record record) {
		super(record);
	}

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setOrderId(String orderId) {
		set("order_id", orderId);
	}

	public String getOrderId() {
		return get("order_id");
	}

	public void setDispatchId(String dispatchId) {
		set("dispatch_id", dispatchId);
	}

	public String getDispatchId() {
		return get("dispatch_id");
	}

	public void setFeedbackTime(java.util.Date feedbackTime) {
		set("feedback_time", feedbackTime);
	}

	public java.util.Date getFeedbackTime() {
		return get("feedback_time");
	}

	public void setFeedbackId(String feedbackId) {
		set("feedback_id", feedbackId);
	}

	public String getFeedbackId() {
		return get("feedback_id");
	}

	public void setFeedbackName(String feedbackName) {
		set("feedback_name", feedbackName);
	}

	public String getFeedbackName() {
		return get("feedback_name");
	}

	public void setUserType(String userType) {
		set("user_type", userType);
	}

	public String getUserType() {
		return get("user_type");
	}

	public void setFeedback(String feedback) {
		set("feedback", feedback);
	}

	public String getFeedback() {
		return get("feedback");
	}

	public void setFeedbackResult(String feedbackResult) {
		set("feedback_result", feedbackResult);
	}

	public String getFeedbackResult() {
		return get("feedback_result");
	}

	public void setFeedbackImg(String feedbackImg) {
		set("feedback_img", feedbackImg);
	}

	public String getFeedbackImg() {
		return get("feedback_img");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}

	public String getRemarks() {
		return get("remarks");
	}

	public void setSiteId(String siteId) {
		set("site_id", siteId);
	}

	public String getSiteId() {
		return get("site_id");
	}

	public void setFeedbackType(String feedbackType) {
		set("feedback_type", feedbackType);
	}

	public String getFeedbackType() {
		return get("feedback_type");
	}

}
