package com.jojowonet.modules.order.adapters;

import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public class HistoryBkOrderDispatchEmployeRel extends JBean {

	public HistoryBkOrderDispatchEmployeRel(Record record) {
		super(record);
	}

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setOrderId(String orderId) {
		set("order_id", orderId);
	}

	public String getOrderId() {
		return get("order_id");
	}

	public void setDispatchId(String dispatchId) {
		set("dispatch_id", dispatchId);
	}

	public String getDispatchId() {
		return get("dispatch_id");
	}

	public void setEmpId(String empId) {
		set("emp_id", empId);
	}

	public String getEmpId() {
		return get("emp_id");
	}

	public void setEmpName(String empName) {
		set("emp_name", empName);
	}

	public String getEmpName() {
		return get("emp_name");
	}

	public void setSiteId(String siteId) {
		set("site_id", siteId);
	}

	public String getSiteId() {
		return get("site_id");
	}

}
