package com.jojowonet.modules.order.adapters;

import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public class HistoryBkOrderSettlement extends JBean {

	public HistoryBkOrderSettlement(Record record) {
		super(record);
	}

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setOrderId(String orderId) {
		set("order_id", orderId);
	}

	public String getOrderId() {
		return get("order_id");
	}

	public void setDispatchId(String dispatchId) {
		set("dispatch_id", dispatchId);
	}

	public String getDispatchId() {
		return get("dispatch_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateBy(String createBy) {
		set("create_by", createBy);
	}

	public String getCreateBy() {
		return get("create_by");
	}

	public void setCreateName(String createName) {
		set("create_name", createName);
	}

	public String getCreateName() {
		return get("create_name");
	}

	public void setFactoryMoney(java.math.BigDecimal factoryMoney) {
		set("factory_money", factoryMoney);
	}

	public java.math.BigDecimal getFactoryMoney() {
		return get("factory_money");
	}

	public void setProfits(java.math.BigDecimal profits) {
		set("profits", profits);
	}

	public java.math.BigDecimal getProfits() {
		return get("profits");
	}

	public void setSumMoney(java.math.BigDecimal sumMoney) {
		set("sum_money", sumMoney);
	}

	public java.math.BigDecimal getSumMoney() {
		return get("sum_money");
	}

	public void setFittingCosts(java.math.BigDecimal fittingCosts) {
		set("fitting_costs", fittingCosts);
	}

	public java.math.BigDecimal getFittingCosts() {
		return get("fitting_costs");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}

	public String getRemarks() {
		return get("remarks");
	}

	public void setServiceMeasures(String serviceMeasures) {
		set("service_measures", serviceMeasures);
	}

	public String getServiceMeasures() {
		return get("service_measures");
	}

	public void setPaymentAmount(java.math.BigDecimal paymentAmount) {
		set("payment_amount", paymentAmount);
	}

	public java.math.BigDecimal getPaymentAmount() {
		return get("payment_amount");
	}

	public void setPaymentDetail(String paymentDetail) {
		set("payment_detail", paymentDetail);
	}

	public String getPaymentDetail() {
		return get("payment_detail");
	}

	public void setCostDetail(String costDetail) {
		set("cost_detail", costDetail);
	}

	public String getCostDetail() {
		return get("cost_detail");
	}

	public void setSiteId(String siteId) {
		set("site_id", siteId);
	}

	public String getSiteId() {
		return get("site_id");
	}

	public void setSettlementDetail(String settlementDetail) {
		set("settlement_detail", settlementDetail);
	}

	public String getSettlementDetail() {
		return get("settlement_detail");
	}

	public void setSettlementTime(java.util.Date settlementTime) {
		set("settlement_time", settlementTime);
	}

	public java.util.Date getSettlementTime() {
		return get("settlement_time");
	}

}
