package com.jojowonet.modules.order.adapters;

import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public class HistoryBkOrderDispatch extends JBean {

	public HistoryBkOrderDispatch(Record record) {
		super(record);
	}

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setOrderId(String orderId) {
		set("order_id", orderId);
	}

	public String getOrderId() {
		return get("order_id");
	}

	public void setDispatchTime(java.util.Date dispatchTime) {
		set("dispatch_time", dispatchTime);
	}

	public java.util.Date getDispatchTime() {
		return get("dispatch_time");
	}

	public void setProcessTime(java.util.Date processTime) {
		set("process_time", processTime);
	}

	public java.util.Date getProcessTime() {
		return get("process_time");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return get("status");
	}

	public void setPromiseFlag(String promiseFlag) {
		set("promise_flag", promiseFlag);
	}

	public String getPromiseFlag() {
		return get("promise_flag");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setDropInTime(java.util.Date dropInTime) {
		set("drop_in_time", dropInTime);
	}

	public java.util.Date getDropInTime() {
		return get("drop_in_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateBy(String updateBy) {
		set("update_by", updateBy);
	}

	public String getUpdateBy() {
		return get("update_by");
	}

	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}

	public String getRemarks() {
		return get("remarks");
	}

	public void setMessengerId(String messengerId) {
		set("messenger_id", messengerId);
	}

	public String getMessengerId() {
		return get("messenger_id");
	}

	public void setMessengerName(String messengerName) {
		set("messenger_name", messengerName);
	}

	public String getMessengerName() {
		return get("messenger_name");
	}

	public void setEmployeId(String employeId) {
		set("employe_id", employeId);
	}

	public String getEmployeId() {
		return get("employe_id");
	}

	public void setEmployeName(String employeName) {
		set("employe_name", employeName);
	}

	public String getEmployeName() {
		return get("employe_name");
	}

	public void setSiteId(String siteId) {
		set("site_id", siteId);
	}

	public String getSiteId() {
		return get("site_id");
	}

	public void setCompletionResult(String completionResult) {
		set("completion_result", completionResult);
	}

	public String getCompletionResult() {
		return get("completion_result");
	}

}
